version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202107-02

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Build Docker containers
          command: |
            set -x
            docker-compose build
      - run:
          name: Mix deps.get & compile
          command: |
            set -x
            docker-compose run app bash -c "mix deps.get"
            docker-compose run app bash -c "mix compile"
      - run:
          name: Npm install in assets directory
          command: |
            set -x
            docker-compose run app bash -c "cd assets && npm i"
      - run:
          name: Compile assets
          command: |
            set -x
            docker-compose run app bash -c "MIX_ENV=prod mix assets.deploy"
      - run:
          name: Mix format
          command: |
            set -x
            docker-compose exec app bash -c "mix format --check-formatted"
      - run:
          name: Mix test
          command: |
            set -x
            docker-compose exec app bash -c "MIX_ENV=test mix test"
      - run:
          name: Mix release
          command: |
            set -x
            docker-compose run app bash -c "MIX_ENV=prod mix release"
      - run:
          name: Run Docker containers
          command: |
            set -x
            docker-compose up -d
            sleep 1
            docker ps -f status=running
            docker-compose logs
      - persist_to_workspace:
          root: .
          paths:
            - ./app/deps
            - ./app/_build
            - ./app/priv
            - ./app/assets/
      - run:
          name: Finish build
          command: |
            set -x
            echo "Finish build"
  deploy:
    executor:
      name: machine-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check directories/files
          command: |
            set -x
            pwd && ls -a && ls app
      - heroku/install
      - heroku/check-authentication
      - run:
          name: Heroku container login, push, release
          working_directory: app
          command: |
            set -x
            ls -a
            heroku container:login
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: Finish deploy
          command: |
            set -x
            echo "Finish deploy"

